# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param items A vector containing the sizes of items to be packed.
#' @param bin_size The maximum capacity of each bin.
#' @return A vector of vectors representing the bins, where each inner vector
#'         contains the sizes of items packed into a single bin.
#' @export
ffd_bin_packing <- function(items, bin_size) {
    .Call(`_StorageOptimisation_ffd_bin_packing`, items, bin_size)
}

#' Insertion sort algorithm using C++
#'
#' @param j an unsorted vector of numeric data
#' @param mem an integer corresponding to the memory size
#' @return a sorted vector
#' @export
naive_storage_Rcpp <- function(j, mem) {
    .Call(`_StorageOptimisation_naive_storage_Rcpp`, j, mem)
}

