# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Insertion sort algorithm using C++
#'
#' @param j an unsorted vector of numeric data
#' @param mem
#' @return a sorted vector
#' @export
naive_storage_Rcpp <- function(j, mem) {
    .Call(`_StorageOptimisation_naive_storage_Rcpp`, j, mem)
}

