# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' First-fit-decreasing bin packing algorithm
#' @param items A vector containing the sizes of items to be packed.
#' @param bin_size The maximum capacity of each bin.
#' @return A vector of vectors representing the bins, where each inner vector
#'         contains the sizes of items packed into a single bin.
#' @export
ffd_bin_packing_Rcpp <- function(items, bin_size) {
    .Call(`_StorageOptimisation_ffd_bin_packing_Rcpp`, items, bin_size)
}

