// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ffd_bin_packing_Rcpp
std::vector<std::vector<int>> ffd_bin_packing_Rcpp(std::vector<int>& games, int storage);
RcppExport SEXP _StorageOptimisation_ffd_bin_packing_Rcpp(SEXP gamesSEXP, SEXP storageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int>& >::type games(gamesSEXP);
    Rcpp::traits::input_parameter< int >::type storage(storageSEXP);
    rcpp_result_gen = Rcpp::wrap(ffd_bin_packing_Rcpp(games, storage));
    return rcpp_result_gen;
END_RCPP
}
// naive_storage_Rcpp
std::vector<std::vector<int>> naive_storage_Rcpp(std::vector<int> j, int mem);
RcppExport SEXP _StorageOptimisation_naive_storage_Rcpp(SEXP jSEXP, SEXP memSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type mem(memSEXP);
    rcpp_result_gen = Rcpp::wrap(naive_storage_Rcpp(j, mem));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StorageOptimisation_ffd_bin_packing_Rcpp", (DL_FUNC) &_StorageOptimisation_ffd_bin_packing_Rcpp, 2},
    {"_StorageOptimisation_naive_storage_Rcpp", (DL_FUNC) &_StorageOptimisation_naive_storage_Rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_StorageOptimisation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
